services:
  vpn:
    image: ghcr.io/thrnz/docker-wireguard-pia:latest
    container_name: vpn
    profiles:
      - vpn
    volumes:
      - ${CONFIG_ROOT:-.}/pia:/pia
      - ${CONFIG_ROOT:-.}/pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LOC=${PIA_LOCATION}
      - USER=${PIA_USER}
      - PASS=${PIA_PASS}
      - QBT_USER=${QBITTORRENT_USERNAME}
      - QBT_PASS=${QBITTORRENT_PASSWORD}
      - LOCAL_NETWORK=${PIA_LOCAL_NETWORK}
      - PORT_FORWARDING=1
      - PORT_PERSIST=1
      - PORT_SCRIPT=/pia-shared/portupdate-qbittorrent.sh
      - FIREWALL=0
      - ACTIVE_HEALTHCHECKS=1
      - RECONNECT=1
      - ALLOW_MISSING_IPTABLES_RULES=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    restart: always

  qbittorrent:
    profiles:
      - vpn
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    healthcheck:
      # Container may fail if the PIA's token expired, so mark as unhealthy when there is no internet connection
      test:
        ["CMD", "curl", "--fail", "http://127.0.0.1:8080", "https://google.com"]
      interval: 1m
      retries: 10
    labels:
      - com.centurylinklabs.watchtower.depends-on=vpn
      - homepage.widget.url=http://vpn:8080
