services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    profiles:
      - portainer
    networks:
      default:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker-compose-nas"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=(Host(`${PORTAINER_HOSTNAME}`))"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - homepage.group=Utilities
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://${PORTAINER_HOSTNAME}
      - homepage.description=Docker Container Management
      - homepage.weight=0
      - homepage.widget.type=portainer
      - homepage.widget.url=http://portainer:9000
      - homepage.widget.env=${PORTAINER_ENV}
      - homepage.widget.key=${PORTAINER_KEY}

volumes:
  portainer:
    name: portainer
